# Problema de las Ocho Reinas

## Contenidos
- [Contenidos](#contenidos)
- [Introducción](#introducción)
- [Planteamiento del Problema](#planteamiento-del-problema)
    - [Estados](#estados)
        - [Representación](#representación)
        - [Estado Inicial](#estado-inicial)
        - [Estado Final](#estado-final)
    - [Condición de Meta](#condición-de-meta)
    - [Función Sucesor](#función-sucesor)
- [Desarrollo del Problema](#desarrollo-del-problema)
    - [Importar Bibliotecas](#importar-bibliotecas)
    - [Declaración del Estado Inicial](#declaración-del-estado-inicial)
    - [Definición de la Función Sucesor](#definición-de-la-función-sucesor)

## Introducción
El problema de las ocho reinas consiste en colocar ocho reinas en un tablero de ajedrez de tamaño de $8\times8$ casillas, de manera que ninguna reina se amenace entre sí; es decir, que ninguna reina sea colocada en la misma columna, fila o diagonal que otra reina.

![8queens_solution1](8queens_solution1.png)

## Planteamiento del Problema
Debido a la naturaleza del problema, se requiere una manera de representar el tablero de ajedrez (dimensiones de $8\times8$), representando cada una de las $64$ casillas, así como la existencia de una reina en alguna de esas casillas, con hasta un máximo de $8$ reinas en total. El problema parte de alguna distribución determinada y termina una vez se haya encontrado una combinación en la que ninguna reina ataque a otra reina y en que todas hayan sido colocadas en el tablero. Esto implica que el problema tiene una profundidad máxima de $8$, si consideramos la profundidad $0$ como el estado en el que no hay ninguna reina sobre el tablero.

### Estados
Cada distribución posible de las reinas en el tablero sería un estado posible. El primer estado, o estado $0$ será aquél con cero reinas en el tablero, mientras que los siguientes $64$ posibles estados serán para representar el tablero con una sola reina; los siguientes $63$ estados serán para el tablero con dos reinas en total, y asi sucesivamente. Esto implica que, para todo el problema, la cantidad total de posibles  estados es $64\times63\times62\times61\times60\times59\times58\times57=178,462,987,637,760$. Por esto mismo, es importante encontrar criterios clave al momento de definir la función sucesoria y las posibles heurísticas.

#### Representación
Para representar el tablero de ajedrez, así como la posición de las reinas en las casillas y, por consiguiente, cada estado, se utilizará una matriz de dimensiones $8\times8$. Esta matriz estará inicialmente llena de ceros, y cada cero representará cada casilla sin reina y que no esté siendo atacada. Para representar a una reina ubicada en la casilla $(i,j)$, a esa posición en la matriz se le asignará un uno. Para representar una casilla vacía que está siendo atacada se utilizará el número dos.

Así pues, el estado $0$ se tendrá de la siguiente forma:
| &nbsp; | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
| --- | --- | --- | --- | --- | --- | --- | --- | ---|
| __0__ | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| __1__ | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| __2__ | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| __3__ | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| __4__ | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| __5__ | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| __6__ | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| __7__ | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |

Un tablero con una sola reina podrá representarse de la siguiente manera:
| &nbsp; | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
| --- | --- | --- | --- | --- | --- | --- | --- | ---|
| __0__ | 2 | 0 | 2 | 0 | 2 | 0 | 0 | 0 |
| __1__ | 0 | 2 | 2 | 2 | 0 | 0 | 0 | 0 |
| __2__ | 2 | 2 | 1 | 2 | 2 | 2 | 2 | 2 |
| __3__ | 0 | 2 | 2 | 2 | 0 | 0 | 0 | 0 |
| __4__ | 2 | 0 | 2 | 0 | 2 | 0 | 0 | 0 |
| __5__ | 0 | 0 | 2 | 0 | 0 | 2 | 0 | 0 |
| __6__ | 0 | 0 | 2 | 0 | 0 | 0 | 2 | 0 |
| __7__ | 0 | 0 | 2 | 0 | 0 | 0 | 0 | 2 |

Y uno con dos reinas, de la siguiente forma:
| &nbsp; | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
| --- | --- | --- | --- | --- | --- | --- | --- | ---|
| __0__ | 2 | 0 | 2 | 2 | 2 | 0 | 0 | 2 |
| __1__ | 0 | 2 | 2 | 2 | 0 | 0 | 2 | 0 |
| __2__ | 2 | 2 | 1 | 2 | 2 | 2 | 2 | 2 |
| __3__ | 0 | 2 | 2 | 2 | 2 | 0 | 0 | 0 |
| __4__ | 2 | 2 | 2 | 1 | 2 | 2 | 2 | 2 |
| __5__ | 0 | 0 | 2 | 2 | 2 | 2 | 0 | 0 |
| __6__ | 0 | 2 | 2 | 2 | 0 | 2 | 2 | 0 |
| __7__ | 2 | 0 | 2 | 2 | 0 | 0 | 2 | 2 |

#### Estado Inicial
Podemos partir del estado $0$, o de cualquier otro estado que cuente con reinas que no se ataquen entre sí.

#### Estado Final

Para este problema existen $92$ soluciones totales. Cualquier distribución que entre en el conjunto de esas soluciones se considerará como un estado final. Estos estados se logran una vez las $8$ reinas han sido colocadas sobre el tablero sin que ningún par de reinas se ataque entre sí.

Un ejemplo de un estado final puede ser:
| &nbsp; | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
| --- | --- | --- | --- | --- | --- | --- | --- | ---|
| __0__ | 2 | 2 | 2 | 1 | 2 | 2 | 2 | 2 |
| __1__ | 2 | 2 | 2 | 2 | 2 | 2 | 1 | 2 |
| __2__ | 2 | 2 | 1 | 2 | 2 | 2 | 2 | 2 |
| __3__ | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 1 |
| __4__ | 2 | 1 | 2 | 2 | 2 | 2 | 2 | 2 |
| __5__ | 2 | 2 | 2 | 2 | 1 | 2 | 2 | 2 |
| __6__ | 1 | 2 | 2 | 2 | 2 | 2 | 2 | 2 |
| __7__ | 2 | 2 | 2 | 2 | 2 | 1 | 2 | 2 |

### Condición de Meta
Para corroborar que se ha alcanzado el estado final, se verificará que la cantidad de reinas colocadas en el tablero sea igual a  $8$. Adicionalmente, se realizarán verificaciones adicionales para determinar si ningún par de reinas se está atacando entre sí. En caso de que ambas condiciones se hayan cumplido, se considerará a dicho estado como una meta o estado final.

### Función Sucesor
La función sucesor recibirá el estado actual en el que se encuentra el tablero. Posteriormente, buscará la primera casilla sin reina o sin ser atacada, y en esa casilla colocará una reina. Finalmente, marcará todas las casillas que esa reina ataque. Haciendo la verificación de casillas atacadas, se tiene una reducción considerable del espacio de estados a analizar.

## Desarrollo del Problema

### Importar Bibliotecas
Para esta parte se requieren bibliotecas básicas, en particular Numpy para el manejo de la matríz que representará al tablero de ajedrez. Adicionalmente, definimos la ruta hacia la biblioteca baile, y de esta obtenemos el módulo para búsqueda simple "SimpleSearch".

In [220]:
import numpy as np
import sys, os
baile_path = os.path.abspath(os.path.join("..","src"))
if not baile_path in sys.path:
    sys.path.append(baile_path)
import SimpleSearch as ss
from importlib import reload
reload(ss)

<module 'SimpleSearch' from '/home/bape119/UMSNH/9thSemester/AI/projects/8QueensProblem/baile-8queens/src/SimpleSearch.py'>

### Declaración del Estado Inicial
Como se mencionó previamente, se partirá del estado $0$. De igual forma, cada estado se representa con una matríz de enteros, donde cada valor puede ser $0$ (casilla vacía y sin atacar), $1$ (casilla con reina) o $2$ (casilla atacada).

Así pues, se define un arreglo bidimensional de Numpy, de dimensiones de $8\times8$ llena de ceros.

In [221]:
state0 = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
])
state0 = tuple([tuple(row) for row in state0])

Este arreglo bidimensional sirve para generar el nodo del estado inicial, a través de la clase node, proporcionada por la biblioteca baile.

In [222]:
startNode = ss.node(state0, op="Inicio")

In [223]:
def printChessBoard(state, numerical=0):
    board = np.array(state)
    for row in board:
        line = " ".join(
            "Q" if val == 1 else "." if val == 0 else "x"
            for val in row
            )
        if numerical == 1:
            line = line + "   " + np.array_str(row)
        print(line)

Hacemos una impresión de las características principales del estado inicial.

In [224]:
print(f"\nOperación: {startNode.op}, Profundidad: {startNode.depth}")
print("Tablero:")
printChessBoard(startNode.state, 1)


Operación: Inicio, Profundidad: 0
Tablero:
. . . . . . . .   [0 0 0 0 0 0 0 0]
. . . . . . . .   [0 0 0 0 0 0 0 0]
. . . . . . . .   [0 0 0 0 0 0 0 0]
. . . . . . . .   [0 0 0 0 0 0 0 0]
. . . . . . . .   [0 0 0 0 0 0 0 0]
. . . . . . . .   [0 0 0 0 0 0 0 0]
. . . . . . . .   [0 0 0 0 0 0 0 0]
. . . . . . . .   [0 0 0 0 0 0 0 0]


### Definición de la Función Sucesor
Como ya se mencionó, esta consiste en colocar una reina en alguna de las casillas que se encuentren disponibles, es decir, sin una reina en ellas y que no estén siendo atacadas.

Para la función sucesor, partimos de un estado $S$. Realizamos una copia de dicho estado, y creamos una lista para sus posibles sucesores.

La intención es recorrer cada casilla del tablero (elemento de la matríz) y, en caso de encontrar una casilla disponible, colocar una reina en ella.

Al encontrarse la casilla, se crea una copia del estado anterior, para generar el nuevo estado. La columna y la fila donde se encuentra la casilla disponible ahora serán atacadas, por lo que se les asigna un $2$.

Una vez la fila y la columna se han indicado como atacadas, se busca la diagonal de arriba a la izquierda hacia abajo a la derecha a la que pertenece la casilla. Para esto, consideramos como referencia la diagonal principal, es decir, aquella que va desde $(0, 0)$ hasta $(7, 7)$, y consideramos un offset, que determina el desplazamiento en diagonales hacia la derecha y arriba (offset positivo) o hacia la izquierda y abajo (offset negativo). Este offset, para la casilla $(i, j)$ se puede calcular como $j-i$.

De igual forma, se busca la anti-diagonal de la casilla, para la que se cumple que todo valor de $(i+k)+(j-k)=i+j$. Es decir, cualquier desplazamiento sobre esa diagonal, dará un valor constante al sumar sus índices. En base a este número también es posible determinar si la anti-diagonal en la que se encuentra la casilla $(i, j)$ está arriba a la izquierda o abajo a la derecha de la anti-diagonal principal.

In [225]:
def placeQueen(node):
    board = np.array(node.state)      # Copia de estado S
    successors = []         # Lista de sucesores
    for i in range (0, len(board)):      # Recorrer filas del tablero
        for j in range (0, len(board)):      # Recorrer columnas del tablero
            if board[i][j] == 0:        # Si la casilla (i, j) está libre
                newBoard = board.copy()     # Se copia el estado anterior

                # Filas y Columnas
                newBoard[i, :] = 2          # Toda la fila i es atacada
                newBoard[:, j] = 2          # Toda la columna j es atacada

                ### Diagonal ###                            # La diagonal vista de esquina superior izquierda a la inferior derecha
                nRows, nCols = newBoard.shape                 # Se determina el número de filas y de columnas
                offset = j - i                                  # Indica en qué diagonal se encuentra la casilla con relación a la diagonal principal
                if offset >= 0:                                 # La diagonal de la casilla está a la derecha y arriba de la diagonal principal
                    rows = np.arange(nRows - offset)               # Se toman las filas de la diagonal, desplazándose una cantidad 'offset' de filas hacia arriba
                    cols = np.arange(nCols - offset) + offset      # Se toman las columnas de la diagonal, desplazándose una cantidad 'offset' de columnas hacia la derecha
                else:                                           # La diagonal de la casilla está a la izquierda y abajo de la diagonal principal
                    rows = np.arange(nRows + offset) - offset      # Se toman las filas de la diagonal, desplazándose una cantidad 'offset' de filas hacia abajo
                    cols = np.arange(nCols + offset)               # Se toman las columnas de la diagonal, desplazándose una cantidad 'offset' de columnas hacia la izquierda
                newBoard[rows, cols] = 2                        # Toda la diagonal es atacada
                
                ### Anti-diagonal ###                       # La diagonal vista de la esquina inferior izquierda a la superior derecha
                diagSum = i + j                                # Se determina la suma de los índices de la antidiagonal
                if diagSum < nRows:                           # La anti-diagonal está a la izquierda y arriba de la anti-diagonal principal
                    antiRows = np.arange(diagSum + 1)             # Se toman las primeras diagSum + 1 filas, compensando el desplazamiento hacia arriba
                    antiCols = diagSum - antiRows                # Se toman las primeras diagSum + 1 columnas, inversamente a las filas, compensando el desplazamiento hacia la izquierda
                else:                                           # La anti-diagonal está a la derecha y abajo de la anti-diagonal principal
                    start_col = diagSum - (nRows - 1)             # Se determina a partir de qué columna tomar
                    antiCols = np.arange(start_col, nCols)        # Se toman las últimas columnas a partir de la determinada, compensando el movimiento hacia la derecha
                    antiRows = diagSum - antiCols                # Se toman las últimas filas, inversamente a las columnas, compensando el desplazamiento hacia abajo
                validIndices = (antiRows >= 0) & (antiRows < nRows) & (antiCols >= 0) & (antiCols < nCols)   # Se validan los límites de las filas y columnas de la anti-diagonal
                antiRows = antiRows[validIndices]            # Se descartan los índices de las filas fuera de los límites
                antiCols = antiCols[validIndices]            # Se descartan los índices de las columnas fuera de los límites
                newBoard[antiRows, antiCols] = 2              # Toda la anti-diagonal es atacada

                newBoard[i][j] = 1                              # Se coloca la reina en la casilla (i, j)

                newBoard = tuple([tuple(row) for row in newBoard])

                op = f"Queen Placed at ({i}, {j})"

                successors.append(ss.node(newBoard, op=op, depth=node.depth+1, parent=node))   # Se añade el nuevo nodo a la lista de sucesores
    return successors

In [189]:
def goalEightQueens(*states):
    start = states[0]
    final = states[1]
    if final == None:
        unique, counts = np.unique(start.state, return_counts=True)
        cellValues = dict(zip(unique, counts))
        return 0 not in cellValues and cellValues.get(1) == 8
    else:
        return (start.state == final.state).all()


In [ ]:
state8 = np.array([
    [2, 2, 2, 1, 2, 2, 2, 2],
    [2, 2, 2, 2, 2, 2, 1, 2],
    [2, 2, 1, 2, 2, 2, 2, 2],
    [2, 2, 2, 2, 2, 2, 2, 1],
    [2, 1, 2, 2, 2, 2, 2, 2],
    [2, 2, 2, 2, 1, 2, 2, 2],
    [1, 2, 2, 2, 2, 2, 2, 2],
    [2, 2, 2, 2, 2, 1, 2, 2],
])
finalNode = ss.node(state8, op="Final")
print(goalEightQueens(startNode, finalNode))

False


In [195]:
bfs = ss.BlindSearch(startNode, placeQueen, goalEightQueens, goal_state=finalNode, strategy="bfs")
dfs = ss.BlindSearch(startNode, placeQueen, goalEightQueens, strategy="dfs")

In [196]:
resbfs = bfs.find()

finished in 118918 iterations
Se acabaron los estados: 51


In [197]:
print(np.array(resbfs.state))

[[2 2 2 1 2 2 2 2]
 [2 2 2 2 2 2 1 2]
 [2 2 1 2 2 2 2 2]
 [2 2 2 2 2 2 2 1]
 [2 1 2 2 2 2 2 2]
 [2 2 2 2 1 2 2 2]
 [1 2 2 2 2 2 2 2]
 [2 2 2 2 2 1 2 2]]


In [198]:
seqbfs = resbfs.getPath()
print("Solution Length: %s" %len(seqbfs))

def print_path(seq):
    for state, op, depth in seq:
        board = np.array(state)

        print(f"\nOperation: {op}, Depth: {depth}")
        print("Board:")

        for row in board:
            line = " ".join(
                "Q" if val == 1 else "." if val == 0 else "x"
                for val in row
            )
            print(line)

print_path(seqbfs)

Solution Length: 9

Operation: start, Depth: 0
Board:
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .
. . . . . . . .

Operation: Queen Placed at (0, 3), Depth: 1
Board:
x x x Q x x x x
. . x x x . . .
. x . x . x . .
x . . x . . x .
. . . x . . . x
. . . x . . . .
. . . x . . . .
. . . x . . . .

Operation: Queen Placed at (1, 6), Depth: 2
Board:
x x x Q x x x x
x x x x x x Q x
. x . x . x x x
x . . x x . x .
. . . x . . x x
. . x x . . x .
. x . x . . x .
x . . x . . x .

Operation: Queen Placed at (2, 2), Depth: 3
Board:
x x x Q x x x x
x x x x x x Q x
x x Q x x x x x
x x x x x . x .
x . x x x . x x
. . x x . x x .
. x x x . . x .
x . x x . . x x

Operation: Queen Placed at (3, 7), Depth: 4
Board:
x x x Q x x x x
x x x x x x Q x
x x Q x x x x x
x x x x x x x Q
x . x x x . x x
. . x x . x x x
. x x x x . x x
x . x x . . x x

Operation: Queen Placed at (4, 1), Depth: 5
Board:
x x x Q x x x x
x x x x x x Q x
x x Q x x x x 