# Problema de las Ocho Reinas

El problema de las ocho reinas consiste en colocar ocho reinas en un tablero de ajedrez de tamaño de $8\times8$ casillas, de manera que ninguna reina se amenace entre sí; es decir, que ninguna reina sea colocada en la misma columna, fila o diagonal que otra reina.

In [52]:
import numpy as np
import sys, os
baile_path = os.path.abspath(os.path.join("..","src"))
if not baile_path in sys.path:
    sys.path.append(baile_path)
import SimpleSearch as ss
from importlib import reload
reload(ss)

<module 'SimpleSearch' from '/home/bape119/UMSNH/9thSemester/AI/projects/8QueensProblem/baile-8queens/src/SimpleSearch.py'>

In [53]:
state0 = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
])

In [54]:
startNode = ss.node(state0, op="start")

In [55]:
print(startNode.state)
print(startNode.parent)
print(startNode.depth)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
None
0


In [56]:
arr = np.zeros((5, 5))
offset = 2  # For the second super-diagonal
val = 9

n_rows, n_cols = arr.shape

# Calculate the valid range for indices based on offset
if offset >= 0:
    rows = np.arange(n_rows - offset)
    cols = np.arange(n_cols - offset) + offset
else: # offset < 0
    rows = np.arange(n_rows + offset) - offset
    cols = np.arange(n_cols + offset)
    
arr[rows, cols] = val
print(arr)

[[0. 0. 9. 0. 0.]
 [0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 9.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [57]:
def placeQueen(node):
    board = node.state
    successors = []
    for i in range (0, 8):
        for j in range (0, 8):
            if board[i][j] == 0:
                newBoard = board.copy()
                ### Columns ###
                newBoard[:, j] = 2

                ### Rows ###
                newBoard[i, :] = 2

                ### Diagonal ###
                n_rows, n_cols = newBoard.shape
                offset = j - i
                if offset >= 0:
                    rows = np.arange(n_rows - offset)
                    cols = np.arange(n_cols - offset) + offset
                else:
                    rows = np.arange(n_rows + offset) - offset
                    cols = np.arange(n_cols + offset)
                newBoard[rows, cols] = 2
                
                ### Anti-diagonal ###
                diag_sum = i + j
                
                # Calculate valid positions on the anti-diagonal
                if diag_sum < n_rows:
                    # Anti-diagonal starts from left edge
                    anti_rows = np.arange(diag_sum + 1)
                    anti_cols = diag_sum - anti_rows
                else:
                    # Anti-diagonal starts from bottom edge
                    start_col = diag_sum - (n_rows - 1)
                    anti_cols = np.arange(start_col, n_cols)
                    anti_rows = diag_sum - anti_cols
                
                # Make sure indices are within bounds
                valid_indices = (anti_rows >= 0) & (anti_rows < n_rows) & (anti_cols >= 0) & (anti_cols < n_cols)
                anti_rows = anti_rows[valid_indices]
                anti_cols = anti_cols[valid_indices]
                
                newBoard[anti_rows, anti_cols] = 2
                newBoard[i][j] = 1
                successors.append(ss.node(newBoard, op="place", depth=node.depth+1, parent=node))
                print(newBoard)
    return successors

In [58]:
successors = placeQueen(startNode)
print(len(successors))

[[1 2 2 2 2 2 2 2]
 [2 2 0 0 0 0 0 0]
 [2 0 2 0 0 0 0 0]
 [2 0 0 2 0 0 0 0]
 [2 0 0 0 2 0 0 0]
 [2 0 0 0 0 2 0 0]
 [2 0 0 0 0 0 2 0]
 [2 0 0 0 0 0 0 2]]
[[2 1 2 2 2 2 2 2]
 [2 2 2 0 0 0 0 0]
 [0 2 0 2 0 0 0 0]
 [0 2 0 0 2 0 0 0]
 [0 2 0 0 0 2 0 0]
 [0 2 0 0 0 0 2 0]
 [0 2 0 0 0 0 0 2]
 [0 2 0 0 0 0 0 0]]
[[2 2 1 2 2 2 2 2]
 [0 2 2 2 0 0 0 0]
 [2 0 2 0 2 0 0 0]
 [0 0 2 0 0 2 0 0]
 [0 0 2 0 0 0 2 0]
 [0 0 2 0 0 0 0 2]
 [0 0 2 0 0 0 0 0]
 [0 0 2 0 0 0 0 0]]
[[2 2 2 1 2 2 2 2]
 [0 0 2 2 2 0 0 0]
 [0 2 0 2 0 2 0 0]
 [2 0 0 2 0 0 2 0]
 [0 0 0 2 0 0 0 2]
 [0 0 0 2 0 0 0 0]
 [0 0 0 2 0 0 0 0]
 [0 0 0 2 0 0 0 0]]
[[2 2 2 2 1 2 2 2]
 [0 0 0 2 2 2 0 0]
 [0 0 2 0 2 0 2 0]
 [0 2 0 0 2 0 0 2]
 [2 0 0 0 2 0 0 0]
 [0 0 0 0 2 0 0 0]
 [0 0 0 0 2 0 0 0]
 [0 0 0 0 2 0 0 0]]
[[2 2 2 2 2 1 2 2]
 [0 0 0 0 2 2 2 0]
 [0 0 0 2 0 2 0 2]
 [0 0 2 0 0 2 0 0]
 [0 2 0 0 0 2 0 0]
 [2 0 0 0 0 2 0 0]
 [0 0 0 0 0 2 0 0]
 [0 0 0 0 0 2 0 0]]
[[2 2 2 2 2 2 1 2]
 [0 0 0 0 0 2 2 2]
 [0 0 0 0 2 0 2 0]
 [0 0 0 2 0 0 2 0]
 [0 0 